"""
Script to build avatar_data.json from browser-scraped data.
Run this in the backend directory.
"""
import json

# All the avatar data collected from typecast.ai/voice-casting
# This combines all batches

avatars = {
    # English voices
    "Alena": "https://static2.typecast.ai/c/250807_alena/alena_main.webp",
    "Anja": "https://static2.typecast.ai/c/250724_anja/anja_main.webp",
    "Elise": "https://static2.typecast.ai/c/250709_elise/elise_main.webp",
    "Wade": "https://static2.typecast.ai/c/250626_wade/wade_main.webp",
    "Nia": "https://static2.typecast.ai/c/250612_nia/nia_main.webp",
    "Walter": "https://static2.typecast.ai/c/250529_walter/walter_main.webp",
    "Tessa": "https://static2.typecast.ai/c/250515_tessa/tessa_main.webp",
    "Echo": "https://static2.typecast.ai/c/250403_echo/echo_main.webp",
    "Doug": "https://static2.typecast.ai/c/250403_doug/doug_main.webp",
    "Janet": "https://static2.typecast.ai/c/250403_janet/janet_main.webp",
    "Audrey": "https://static2.typecast.ai/c/250327_audrey/audrey_main.webp",
    "Nova": "https://static2.typecast.ai/c/250327_nova/nova_main.webp",
    "Elias": "https://static2.typecast.ai/c/250320_elias/elias_main.webp",
    "Riley": "https://static2.typecast.ai/c/250320_riley/riley_main.webp",
    "Verna": "https://static2.typecast.ai/c/250320_verna/verna_main.webp",
    "Sylvia": "https://static2.typecast.ai/c/250313_sylvia/sylvia_main.webp",
    "Kanno": "https://static2.typecast.ai/c/250313_kanno/kanno_main.webp",
    "Zoey": "https://static2.typecast.ai/c/250313_zoey/zoey_main.webp",
    "Valerie": "https://static2.typecast.ai/c/250306_valerie/valerie_main.webp",
    "Chad": "https://static2.typecast.ai/c/250306_chad/chad_main.webp",
    "Rusty": "https://static2.typecast.ai/c/250227_rusty/rusty_main.webp",
    "Gus": "https://static2.typecast.ai/c/250227_gus/gus_main.webp",
    "Aaron": "https://static2.typecast.ai/c/250220_aaron/aaron_main.webp",
    "Damian": "https://static2.typecast.ai/c/250213_damian/damian_main.webp",
    "Margot": "https://static2.typecast.ai/c/250206_margot/margot_main.webp",
    "Logan": "https://static2.typecast.ai/c/250123_logan/logan_main.webp",
    "Jackson": "https://static2.typecast.ai/c/250123_jackson/jackson_main.webp",
    "Viktor": "https://static2.typecast.ai/c/250116_viktor/viktor_main.webp",
    "Benny": "https://static2.typecast.ai/c/250116_benny/benny_main.webp",
    "Hugh": "https://static2.typecast.ai/c/250109_hugh/hugh_main.webp",
    "Hailey": "https://static2.typecast.ai/c/250109_hailey/hailey_main.webp",
    "Carl": "https://static2.typecast.ai/c/240103_carl/carl_main.webp",
    "Victoria": "https://static2.typecast.ai/c/240103_victoria/victoria_main.webp",
    "Paige": "https://static2.typecast.ai/c/241219_paige/paige_main.webp",
    "Kelsey": "https://static2.typecast.ai/c/241219_kelsey/kelsey_main.webp",
    "Grace": "https://static2.typecast.ai/c/241211_grace/grace_main.webp",
    "Oliver": "https://static2.typecast.ai/c/241211_oliver/oliver_main.webp",
    "Skylar": "https://static2.typecast.ai/c/241205_skylar/skylar_main.webp",
    "Jeff": "https://static2.typecast.ai/c/241205_jeff/jeff_main.webp",
    "Ravi": "https://static2.typecast.ai/c/241128_ravi/ravi_main.webp",
    "Lucille": "https://static2.typecast.ai/c/241128_lucille/lucille_main.webp",
    "Dean": "https://static2.typecast.ai/c/241121_dean/dean_main.webp",
    "Shana": "https://static2.typecast.ai/c/241121_shana/shana_main.webp",
    "Chase": "https://static2.typecast.ai/c/241114_chase/chase_main.webp",
    "Harper": "https://static2.typecast.ai/c/241114_harper/harper_main.webp",
    "Bruce": "https://static2.typecast.ai/c/241107_bruce/bruce_main.webp",
    "Dylan": "https://static2.typecast.ai/c/241107_dylan/dylan_main.webp",
    "Starling": "https://static2.typecast.ai/c/240814_starling/__abtest__a/starling_main.webp",
    "Robert": "https://static2.typecast.ai/c/240814_robert/__abtest__a/robert_main.webp",
    "Chloe": "https://static2.typecast.ai/c/240802_chloe/__abtest__a/chloe_main.webp",
    "Landon": "https://static2.typecast.ai/c/240502_landon/__abtest__a/landon_main.webp",
    "Kristen": "https://static2.typecast.ai/c/240425_kristen/__abtest__a/kristen_main.webp",
    "Ron": "https://static2.typecast.ai/c/240418_ron/__abtest__a/ron_main.webp",
    "Carol": "https://static2.typecast.ai/c/240418_carol/__abtest__a/carol_main.webp",
    "Chester": "https://static2.typecast.ai/c/240404_chester/chester_main.webp",
    "Patricia": "https://static2.typecast.ai/c/240404_patricia/__abtest__a/patricia_main.webp",
    "Larry": "https://static2.typecast.ai/c/240223_larry/__abtest__a/larry_main.webp",
    "Royce": "https://static2.typecast.ai/c/240213_royce/royce_main.webp",
    "Callan": "https://static2.typecast.ai/c/240202_callan/callan_main.webp",
    "Simon": "https://static2.typecast.ai/c/240126_simon/simon_main.webp",
    "Avery": "https://static2.typecast.ai/c/240104_avery/avery_main.webp",
    "Lloyd": "https://static2.typecast.ai/231130_lloyd/lloyd_main.webp",
    "Rita": "https://static2.typecast.ai/c/231124_rita/rita_main.webp",
    "Norah": "https://static2.typecast.ai/c/231026_norah/nora_main.webp",
    "Captain Bill": "https://static2.typecast.ai/c/230927_captainbill/captainbill_main.webp",
    "Billie": "https://static2.typecast.ai/c/230510_billie/billie_main.webp",
    "Maisie": "https://static2.typecast.ai/c/230504_maisie/maisie_main.webp",
    "Eman": "https://static2.typecast.ai/c/230427_eman/eman_main.webp",
    "River": "https://static2.typecast.ai/c/230419_river/river_main.webp",
    "Jake": "https://static2.typecast.ai/c/230413_jake/jake_main.webp",
    "Amber": "https://static2.typecast.ai/c/230407_amber/amber_main.webp",
    "Koombo": "https://static2.typecast.ai/c/230331_koombo/koombo_main.webp",
    "Wildflame": "https://static2.typecast.ai/c/230331_wildflame/wildflame_main.webp",
    "Jenna": "https://static2.typecast.ai/c/230323_jenna/jenna2_main.webp",
    "Caitlyn": "https://static2.typecast.ai/c/230316_caitlyn/caitlyn_main.webp",
    "Nathan": "https://static2.typecast.ai/c/230309_nathan/nathan_main.webp",
    "Klip Kim": "https://static2.typecast.ai/c/230302_klip/klip_main.webp",
    "Natalie": "https://static2.typecast.ai/c/230223_natalie/natalie_main.webp",
    "Catherine": "https://static2.typecast.ai/c/230216_catherine/catherine_main.webp",
    "Brad": "https://static2.typecast.ai/c/230209_imagefix/brad2_main.webp",
    "Lydia": "https://static2.typecast.ai/c/230201_lydia/lydia_main.webp",
    "Neel": "https://static2.typecast.ai/c/230127_neel/neel_main.webp",
    "Maddie": "https://static2.typecast.ai/c/230118_maddie/maddie_main.webp",
    "April": "https://static2.typecast.ai/c/230111_april/april_main.webp",
    "Cole": "https://static2.typecast.ai/c/230105_cole/cole_main.webp",
    "Graham": "https://static2.typecast.ai/c/221227_graham/graham_main.webp",
    "Charlotte": "https://static2.typecast.ai/c/221222_charlotte/charlotte_main.webp",
    "Liz": "https://static2.typecast.ai/c/221215_liz/liz_main.webp",
    "Noel": "https://static2.typecast.ai/c/221206_noel/noel_main.webp",
    "Bell": "https://static2.typecast.ai/c/221206_bell/bell_main.webp",
    "Buddy": "https://static2.typecast.ai/c/221206_buddy/buddy_main.webp",
    "Santa Claus": "https://static2.typecast.ai/c/221130_santaclaus/santa_main.webp",
    "Mrs. Claus": "https://static2.typecast.ai/c/221130_mrsclaus/mrsclaus_main.webp",
    "Patrick": "https://static2.typecast.ai/c/221122_patrick/patrick_main.webp",
    "Jodie": "https://static2.typecast.ai/c/221122_jodie/jodie_main.webp",
    "Athena": "https://static2.typecast.ai/c/221116_athena/athena_main.webp",
    "Abigail": "https://static2.typecast.ai/c/221109_abigail/abigail_main.webp",
    "Philip": "https://static2.typecast.ai/c/241118_philip/philip_main.webp",
    "Millie": "https://static2.typecast.ai/c/221027_millie/millie_main.webp",
    "Annabelle the Ghost": "https://static2.typecast.ai/c/221021_annabelle/annabelle_main.webp",
    "Frankenstein": "https://static2.typecast.ai/c/221019_franken/franken_main.webp",
    "Jack-o'-Lantern": "https://static2.typecast.ai/c/221019_jacko/jacko_main.webp",
    "Killian the Vampire": "https://static2.typecast.ai/c/221019_vampire/vampire_main.webp",
    "Sabrina the Witch": "https://static2.typecast.ai/c/221019_witch/witch_main.webp",
    "Henry": "https://static2.typecast.ai/c/221013_henry/henry_main.webp",
    "Tina": "https://static2.typecast.ai/c/221013_tina/tina_main.webp",
    "Justin": "https://static2.typecast.ai/c/221005_justin/justin_main.webp",
    "Ben": "https://static2.typecast.ai/c/220928_ben/ben_main.webp",
    "West": "https://static2.typecast.ai/c/220921_west/west_main.webp",
    "Lindsay": "https://static2.typecast.ai/c/220921_lindsay/lindsay_main.webp",
    "Rex": "https://static2.typecast.ai/c/220915_rex/rex_main.webp",
    "Rebecca": "https://static2.typecast.ai/c/220831_rebecca/rebecca_main.webp",
    "Agatha": "https://static2.typecast.ai/c/220824_agatha/agatha_main.webp",
    "Sean": "https://static2.typecast.ai/c/220824_sean/sean_main.webp",
    "Rachel": "https://static2.typecast.ai/c/220824_rachel/rachel_main.webp",
    "Leo": "https://static2.typecast.ai/c/220817_leo/leo_main.webp",
    "Ella": "https://static2.typecast.ai/c/220817_ella/ella_main.webp",
    "Stephanie": "https://static2.typecast.ai/c/220810_stephanie/stephanie_main.webp",
    "Owen": "https://static2.typecast.ai/c/220802_owen/owen_main.webp",
    "Mia": "https://static2.typecast.ai/c/220727_mia/mia_main.webp",
    "Cyrus": "https://static2.typecast.ai/c/220719_cyrus/cyrus_main.webp",
    "Tim": "https://static2.typecast.ai/c/220713_tim/tim_main.webp",
    "Samantha": "https://static2.typecast.ai/c/220628_samantha/samantha_main.webp",
    "Joshua": "https://static2.typecast.ai/c/220628_joshua/joshua_main.webp",
    "Olivia": "https://static2.typecast.ai/c/220614_olivia/olivia_main.webp",
    "Tyson": "https://static2.typecast.ai/c/220608_tyson/tyson_main.webp",
    "Sophia": "https://static2.typecast.ai/c/220531_sophia/sophia_main.webp",
    "Ruby": "https://static2.typecast.ai/c/220531_ruby/ruby_main.webp",
    "Claire": "https://static2.typecast.ai/c/220524_claire/claire_main.webp",
    "Sara": "https://static2.typecast.ai/c/220524_sara/sara_main.webp",
    "P-0150N": "https://static2.typecast.ai/c/220517_p0150n/p0150n_main.webp",
    "Kelly": "https://static2.typecast.ai/c/220517_kelly2/kelly2_main.webp",
    "Alex": "https://static2.typecast.ai/c/220504_alex/alex_main.webp",
    "Neoguard": "https://static2.typecast.ai/c/220504_neoguard/neoguard_main.webp",
    "Edward": "https://static2.typecast.ai/c/220420_edward/__abtest__a/edward_main.webp",
    "Koombot": "https://static2.typecast.ai/c/230331_koombot/koombot_main.webp",
    "Hans": "https://static2.typecast.ai/c/All/hans.webp",
    "Angela": "https://static2.typecast.ai/c/All/angela.webp",
    "Matthew": "https://static2.typecast.ai/c/All/matthew.webp",
    "Oscar": "https://static2.typecast.ai/c/All/oscar.webp",
    "Helena": "https://static2.typecast.ai/c/All/helena.webp",
    "Vincent": "https://static2.typecast.ai/c/All/vincent.webp",
    "Noa": "https://static2.typecast.ai/c/All/noah.webp",
    "Aiden": "https://static2.typecast.ai/c/All/aiden.webp",
    "Katie": "https://static2.typecast.ai/c/All/katie.webp",
    "Ryan": "https://static2.typecast.ai/c/All/ryan.webp",
    "Betty": "https://static2.typecast.ai/c/All/betty.webp",
    "Emma": "https://static2.typecast.ai/c/All/emma.webp",
    "Peter": "https://static2.typecast.ai/c/All/peter.webp",
    "Carlos": "https://static2.typecast.ai/c/All/carlos.webp",
    "Michael": "https://static2.typecast.ai/c/All/michael.webp",
    "Dollar Jr.": "https://static2.typecast.ai/c/All/dollarjr.webp",
    "Rudolph": "https://static2.typecast.ai/c/All/rudolph.webp",
    "Santa": "https://static2.typecast.ai/c/All/santa.webp",
    "Slushy": "https://static2.typecast.ai/c/All/slushy.webp",
    "Vivien": "https://static2.typecast.ai/c/All/vivien.webp",
    "Dan": "https://static2.typecast.ai/c/All/dan.webp",
    "Vanessa": "https://static2.typecast.ai/c/All/vanessa.webp",
    "Kevin": "https://static2.typecast.ai/c/All/kevin.webp",
    "Cameron": "https://static2.typecast.ai/c/All/cameron.webp",
    "Sindarin": "https://static2.typecast.ai/c/All/sindarin.webp",
    "Furnando": "https://static2.typecast.ai/c/All/furnando.webp",
    "Keybo": "https://static2.typecast.ai/c/All/keybo.webp",
    "Hellen": "https://static2.typecast.ai/c/All/hellen.webp",
    "David": "https://static2.typecast.ai/c/All/david.webp",
    "Jack": "https://static2.typecast.ai/c/All/jack.webp",
    "Annie": "https://static2.typecast.ai/c/All/annie.webp",
    "George": "https://static2.typecast.ai/c/All/george.webp",
    "Liam": "https://static2.typecast.ai/c/All/liam.webp",
    "Margaret": "https://static2.typecast.ai/c/All/margaret.webp",
    "Xavier": "https://static2.typecast.ai/c/All/xavier.webp",
    "Tommy": "https://static2.typecast.ai/c/All/tommy.webp",
    "Nana": "https://static2.typecast.ai/c/All/nana.webp",
    "Duke": "https://static2.typecast.ai/c/220531_char_numain/nuduke_numain.webp",
    "Doughnut": "https://static2.typecast.ai/c/All/doughnut.webp",
    "Newscaster John": "https://static2.typecast.ai/c/All/john.webp",
    "Reporter Catalina": "https://static2.typecast.ai/c/All/catarina.webp",
    "Jimmy": "https://static2.typecast.ai/c/All/jimmy.webp",
    "Icarus": "https://static2.typecast.ai/c/All/icarus.webp",
    "Uncle Hank": "https://static2.typecast.ai/c/All/hank.webp",
    "Glenda": "https://static2.typecast.ai/c/All/glenda.webp",
    "Jennifer": "https://static2.typecast.ai/c/All/jennifer.webp",
    "Camila": "https://static2.typecast.ai/c/221030_recovery/camila_main.webp",
    "Mark": "https://static2.typecast.ai/c/All/mark.webp",
    # Korean voices  
    "Minsang": "https://static2.typecast.ai/c/All/minsang.webp",
    "Hana": "https://static2.typecast.ai/c/All/hana.webp",
    "Tian": "https://static2.typecast.ai/c/All/tian.webp",
    "Jungsook": "https://static2.typecast.ai/c/251224_jungsook/jungsook_main.webp",
    "Byunghun": "https://static2.typecast.ai/c/251217_byunghun/byunghun_main.webp",
    "Daeun": "https://static2.typecast.ai/c/251127_daeun/daeun_main.webp",
    "Moonjung": "https://static2.typecast.ai/c/251023_moonjung/moonjung_main.webp",
    "Minuk": "https://static2.typecast.ai/c/251016_minuk/minuk_main.webp",
    "Leehyun": "https://static2.typecast.ai/c/251002_leehyun/leehyun_main.webp",
    "Kangil": "https://static2.typecast.ai/c/250925_kangil/kangil_main.webp",
    "Gowoon": "https://static2.typecast.ai/c/250717_gowoon/gowoon_main.webp",
    "Wonwoo": "https://static2.typecast.ai/c/250709_wonwoo/wonwoo_main.webp",
    "Seheon": "https://static2.typecast.ai/c/250703_seheon/seheon_main.webp",
    "Cheolhoon": "https://static2.typecast.ai/c/250626_cheolhoon/cheolhoon_main.webp",
    "Seojin": "https://static2.typecast.ai/c/250619_seojin/seojin_main.webp",
    "Jaesun": "https://static2.typecast.ai/c/250612_jaesun/jaesun_main.webp",
    "Rayeon": "https://static2.typecast.ai/c/250605_rayeon/rayeon_main.webp",
    "Soye": "https://static2.typecast.ai/c/250528_soye/soye_main.webp",
    "Hyeongjin": "https://static2.typecast.ai/c/250522_hyeongjin/hyeongjin_main.webp",
    "Piljae": "https://static2.typecast.ai/c/250515_piljae/piljae_main.webp",
    "Youngmok": "https://static2.typecast.ai/c/250508_youngmok/youngmok_main.webp",
    "Jain": "https://static2.typecast.ai/c/250424_jain/jain_main.webp",
    "Taewoo": "https://static2.typecast.ai/c/250417_taewoo/taewoo_main.webp",
    "Jongdae": "https://static2.typecast.ai/c/250326_jongdae/jongdae_main.webp",
    "Eunsol": "https://static2.typecast.ai/c/250320_eunsol/eunsol_main.webp",
    "Sewoo": "https://static2.typecast.ai/c/250313_sewoo/sewoo_main.webp",
    "Yejin": "https://static2.typecast.ai/250306_yejin2/yejin_main.webp",
    "Igyeom": "https://static2.typecast.ai/c/250227_igyeom/igyeom_main.webp",
    "Soyi": "https://static2.typecast.ai/c/250220_soyi/soyi_main.webp",
    "Dabin": "https://static2.typecast.ai/c/250213_dabin/dabin_main.webp",
    "Rowoon": "https://static2.typecast.ai/c/250206_rowoon/rowoon_main.webp",
    "Seungjae": "https://static2.typecast.ai/c/250123_seungjae/seungjae_main.webp",
    "Haerang": "https://static2.typecast.ai/c/250116_haerang/haerang_main.webp",
    "Jangwoon": "https://static2.typecast.ai/c/250116_jangwoon/jangwoon_main.webp",
    "Hangyeol": "https://static2.typecast.ai/c/250109_hangyeol/hangyeol_main.webp",
    "Miso": "https://static2.typecast.ai/c/250109_miso/miso_main.webp",
    "Changhee": "https://static2.typecast.ai/c/250102_changhee/changhee_main.webp",
    "Babilon": "https://static2.typecast.ai/c/250102_babilon/babilon_main.webp",
    "Ael": "https://static2.typecast.ai/c/241226_ael/ael_main.webp",
    "Kyumin": "https://static2.typecast.ai/c/241219_kyumin/kyumin_main.webp",
    "Suyoon": "https://static2.typecast.ai/c/241219_suyoon/suyoon_main.webp",
    "Kwonil": "https://static2.typecast.ai/c/241212_kwonil/kwonil_main.webp",
    "Wonkyung": "https://static2.typecast.ai/c/241212_wonkyung/wonkyung_main.webp",
    "Chungah": "https://static2.typecast.ai/c/241205_chungah/chungah_main.webp",
    "Arin": "https://static2.typecast.ai/c/241205_arin/arin_main.webp",
    "Goat Kim": "https://static2.typecast.ai/c/241128_goatkim/goatkim_main.webp",
    "Hwimin": "https://static2.typecast.ai/c/241128_hwimin/hwimin_main.webp",
    "Jinhan": "https://static2.typecast.ai/c/241121_jinhan/jinhan_main.webp",
    "Yuri": "https://static2.typecast.ai/c/241121_yuri/yuri_main.webp",
    "Monggun": "https://static2.typecast.ai/c/241111_monggun/monggun_main.webp",
    "Jinhee": "https://static2.typecast.ai/c/241111_jinhee/jinhee_main.webp",
    "Hyun": "https://static2.typecast.ai/c/241111_hyun/hyun_main.webp",
    "Jaekyung": "https://static2.typecast.ai/c/241111_jaekyung/jaekyung_main.webp",
    "Minju": "https://static2.typecast.ai/c/241111_minju/minju_main.webp",
    "Seolhwa": "https://static2.typecast.ai/c/241111_seolhwa/seolhwa_main.webp",
    "Hanyoung": "https://static2.typecast.ai/c/241111_hanyoung/hanyoung_main.webp",
    "Gunseok": "https://static2.typecast.ai/c/241111_gunseok/gunseok_main.webp",
    "Youngji": "https://static2.typecast.ai/c/241111_youngji/youngji_main.webp",
    "Juyoung": "https://static2.typecast.ai/c/240926_juyoung/juyoung_main.webp",
    "Han Taesung Caster": "https://static2.typecast.ai/c/240926_han%20taesung%20caster/han%20taesung%20caster_main.webp",
    "Sumin": "https://static2.typecast.ai/c/240912_sumin/sumin_main256.webp",
    "Junseong": "https://static2.typecast.ai/c/240912_junseong/junseong_main.webp",
    "Seohee": "https://static2.typecast.ai/c/240905_seohee/seohee_main.webp",
    "Yoonseo": "https://static2.typecast.ai/c/240905_yoonseo/yoonseo_main.webp",
    "Dohyun": "https://static2.typecast.ai/c/240829_dohyun/dohyun_main.webp",
    "Hyunji": "https://static2.typecast.ai/c/240829_hyunji/hyunji_main.webp",
    "Taemin": "https://static2.typecast.ai/c/240822_taemin/taemin_main.webp",
    "Inhye": "https://static2.typecast.ai/c/240822_inhye/inhye_main.webp",
    "Wonho": "https://static2.typecast.ai/c/240816_wonho/wonho_main.webp",
    "Seoyoon": "https://static2.typecast.ai/c/240816_seoyoon/seoyoon_main.webp",
    "Chiho": "https://static2.typecast.ai/c/240808_chiho/chiho_main.webp",
    "Minchae": "https://static2.typecast.ai/c/240808_minchae/minchae_main.webp",
    "Yeseul": "https://static2.typecast.ai/c/240801_yeseul/yeseul_main.webp",
    "Seungho": "https://static2.typecast.ai/c/240801_seungho/seungho_main.webp",
    "Wangkwon": "https://static2.typecast.ai/c/240725_wangkwon/wangkwon_main.webp",
    "Siwoo": "https://static2.typecast.ai/c/240719_siwoo/siwoo_main.webp",
    "Minjung": "https://static2.typecast.ai/c/240719_minjung/minjung_main.webp",
    "Sua": "https://static2.typecast.ai/c/240719_sua/sua_main.webp",
    "Woosung": "https://static2.typecast.ai/c/240711_woosung/woosung_main.webp",
    "Deokhwan": "https://static2.typecast.ai/c/240704_deokhwan/deokhwan_main.webp",
    "Jungseok": "https://static2.typecast.ai/c/240704_jungseok/jungseok_main.webp",
    "Hyemin": "https://static2.typecast.ai/c/240627_hyemin/hyemin_main.webp",
    "Sio": "https://static2.typecast.ai/c/240620_sio/sio_main.webp",
    "Sojin": "https://static2.typecast.ai/c/240613_sojin/sojin_main.webp",
    "Sunghoon": "https://static2.typecast.ai/c/240607_sunghoon/sunghoon_main.webp",
    "Azzi": "https://static2.typecast.ai/c/240530_azzi/azzi_main.webp",
    "Ggami": "https://static2.typecast.ai/c/240530_ggami/ggami_main.webp",
    "Yunbin": "https://static2.typecast.ai/c/240524_yunbin/yunbin_main.webp",
    "Hyera": "https://static2.typecast.ai/c/240524_hyera/hyera_main.webp",
    "Munsu": "https://static2.typecast.ai/c/240516_munsu/munsu_main.webp",
    "Insun": "https://static2.typecast.ai/c/240516_insun/insun_main.webp",
    "Roro": "https://static2.typecast.ai/c/240509_roro/roro_main.webp",
    "Geunseok": "https://static2.typecast.ai/c/240509_geunseok/geunseok_main.webp",
    "Eunchae": "https://static2.typecast.ai/c/240502_eunchae/eunchae_main.webp",
    "Duman": "https://static2.typecast.ai/c/240502_duman/duman_main.webp",
    "Ijun": "https://static2.typecast.ai/c/240425_Ijun/Ijun_main.webp",
    "Naeun": "https://static2.typecast.ai/c/240425_naeun/naeun_main.webp",
    "Mirine": "https://static2.typecast.ai/c/240418_mirine/mirine_main.webp",
    "Chunsik Kang": "https://static2.typecast.ai/c/240418_kangchunsik/kangchunsik_main.webp",
    "Hansol": "https://static2.typecast.ai/c/240411_hansol/hansol_main.webp",
    "Bongman Kim": "https://static2.typecast.ai/c/240411_kimbongman/kimbongman_main.webp",
    "Gongchul": "https://static2.typecast.ai/c/240403_gongchul/gongchul_main.webp",
    "Eunbin": "https://static2.typecast.ai/c/240403_eunbin/eunbin_main.webp",
    "Cherry": "https://static2.typecast.ai/c/240329_cherry/cherry_main.webp",
    "Taeji": "https://static2.typecast.ai/c/240329_taeji/taeji_main.webp",
    "Jinung": "https://static2.typecast.ai/c/240321_jinung/jinung_main.webp",
    "Hayul": "https://static2.typecast.ai/c/240321_hayul/hayul_main.webp",
    "Yeeun": "https://static2.typecast.ai/c/240314_yeeun/yeeun_main.webp",
    "Jihyun": "https://static2.typecast.ai/c/240314_jihyun/jihyun_main.webp",
    "Munseok": "https://static2.typecast.ai/c/240307_munseok/munseok_main.webp",
    "Yumi": "https://static2.typecast.ai/c/240307_yumi/yumi_main.webp",
}

print(f"Total avatars: {len(avatars)}")

# Save to file
with open("avatar_data.json", "w", encoding="utf-8") as f:
    json.dump(avatars, f, indent=2, ensure_ascii=False)

print("Saved to avatar_data.json")
